#!/usr/bin/env bash
# scaleway-interactive.sh — 极度友好的 Scaleway 部署交互脚本
# 功能：配置 Zen Key、API Key、打包 function.zip、本地联调、一键部署到 Scaleway Functions / Containers
# 设计目标：零学习成本、彩色动效、容错、可重复执行、支持非交互 --yes / CI
set -euo pipefail

# ─────────────────────────────────────────────
# 基础配置
# ─────────────────────────────────────────────
VERSION="1.5.0-scaleway"
ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"
ENV_FILE=".env.scaleway"
STATE_FILE=".scaleway.state"
FUNCTION_ZIP="function.zip"
DEFAULT_PORT=10000

# 颜色
if [[ -t 1 ]]; then
  RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[0;33m'; BLUE='\033[0;34m'
  MAGENTA='\033[0;35m'; CYAN='\033[0;36m'; BOLD='\033[1m'; DIM='\033[2m'; NC='\033[0m'
else
  RED=''; GREEN=''; YELLOW=''; BLUE=''; MAGENTA=''; CYAN=''; BOLD=''; DIM=''; NC=''
fi
USE_TUI=false
if command -v whiptail >/dev/null 2>&1; then USE_TUI=false; fi # whiptail可选，但我们用纯bash彩色更可控

# 状态
NON_INTERACTIVE=false
DO_PACK=false
DO_TEST=false
DO_DEPLOY_FN=false
DO_DEPLOY_CT=false
DO_CLEAN=false
DRY_RUN=false

# ─────────────────────────────────────────────
# 工具函数
# ─────────────────────────────────────────────
banner() {
  clear 2>/dev/null || true
  cat <<'EOF'
  ____                   _          ___   _   ____ ___
 / ___|  ___ __ _ ___  _| | _____ _|_ _| / | |___ \_ _|
 \___ \ / __/ _` | \ \/ / |/ / _` || |  | |   __) | |
  ___) | (_| (_| |>  <|   < (_| || |  | |  / __/| |
 |____/ \___\__,_/_/\_\_|\_\__,_|___| |_| |_____|___|
        Scaleway Edition • opencode2api
EOF
  echo -e "${DIM}  Version ${VERSION} | https://github.com/TiaraBasori/OpenCode2API${NC}"
  echo -e "${DIM}  Minimal Scaleway patch • handler.js + src/config.js${NC}"
  echo ""
}

log_step()  { echo -e "${BLUE}▸${NC} ${BOLD}$*${NC}"; }
log_ok()    { echo -e "${GREEN}  ✓${NC} $*"; }
log_warn()  { echo -e "${YELLOW}  ⚠${NC} $*"; }
log_err()   { echo -e "${RED}  ✗${NC} $*"; }
log_info()  { echo -e "${DIM}    $*${NC}"; }
hr()        { echo -e "${DIM}────────────────────────────────────────────────────────${NC}"; }

ask() {
  local prompt="$1" default="${2:-}" var
  if [[ "$NON_INTERACTIVE" == true ]]; then
    echo "$default"
    return
  fi
  if [[ -n "$default" ]]; then
    echo -ne "${CYAN}?${NC} ${prompt} ${DIM}[$default]${NC}: " >&2
  else
    echo -ne "${CYAN}?${NC} ${prompt}: " >&2
  fi
  read -r var || var=""
  if [[ -z "$var" ]]; then var="$default"; fi
  echo "$var"
}

ask_secret() {
  local prompt="$1" default="${2:-}" var
  if [[ "$NON_INTERACTIVE" == true ]]; then
    echo "$default"
    return
  fi
  if [[ -n "$default" ]]; then
    echo -ne "${CYAN}?${NC} ${prompt} ${DIM}[已配置, 回车保持]${NC}: " >&2
  else
    echo -ne "${CYAN}?${NC} ${prompt}: " >&2
  fi
  # masked input
  read -rs var || var=""
  echo "" >&2
  if [[ -z "$var" ]]; then var="$default"; fi
  echo "$var"
}

confirm() {
  local prompt="$1" default="${2:-y}"
  if [[ "$NON_INTERACTIVE" == true ]]; then
    [[ "$default" == "y" ]] && return 0 || return 1
  fi
  local ans
  ans=$(ask "$prompt (y/n)" "$default")
  [[ "$ans" =~ ^[Yy]$ ]] || [[ "$ans" == "是" ]]
}

generate_api_key() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 16
  else
    # fallback: /dev/urandom
    head -c 16 /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

check_deps() {
  log_step "预检依赖"
  local ok=true
  for cmd in node npm zip curl; do
    if command -v "$cmd" >/dev/null 2>&1; then
      log_ok "$cmd $( $cmd --version 2>&1 | head -n1 | tr -d '\n')"
    else
      log_err "$cmd 未安装 — 请先安装 $cmd"
      ok=false
    fi
  done
  if ! node -e "process.exit(parseInt(process.versions.node.split('.')[0])>=18?0:1)" 2>/dev/null; then
    log_err "Node.js <18，需升级到 18+ (Scaleway runtime node18/20/22)"
    ok=false
  fi
  if ! command -v scw >/dev/null 2>&1; then
    log_warn "scw CLI 未安装 — 仅影响一键部署，手动上传 zip 仍可用"
    log_info "安装: curl -s https://raw.githubusercontent.com/scaleway/scaleway-cli/master/scripts/get.sh | sh"
  else
    log_ok "scw $(scw version 2>&1 | head -n1)"
  fi
  if ! command -v docker >/dev/null 2>&1; then
    log_info "docker 未安装 — Container 部署将跳过"
  else
    log_ok "docker $(docker --version 2>&1 | head -n1)"
  fi
  hr
  if [[ "$ok" == false && "$NON_INTERACTIVE" == true ]]; then
    log_err "依赖缺失，非交互模式下无法继续"; exit 1
  fi
  if [[ "$ok" == false ]]; then
    if ! confirm "依赖不全，仍继续?" "n"; then exit 1; fi
  fi
}

load_env() {
  # 加载已有配置
  if [[ -f "$ENV_FILE" ]]; then
    # shellcheck disable=SC1090
    set -a; source "$ENV_FILE" 2>/dev/null || true; set +a
    log_info "已加载 $ENV_FILE"
  fi
  if [[ -f .env ]]; then
    log_info "检测到 .env（Docker 用），Functions 将优先使用 $ENV_FILE"
  fi
}

save_env() {
  local api_key="$1" zen_key="$2" server_pw="$3"
  cat > "$ENV_FILE" <<EOF
# Generated by scaleway-interactive.sh on $(date -Iseconds)
# 用于 Scaleway Functions / Containers 的环境变量
API_KEY=$api_key
OPENCODE_ZEN_API_KEY=$zen_key
OPENCODE_SERVER_PASSWORD=$server_pw
# 可选：覆盖端口/行为（Functions 已自动处理 PORT=8080）
# OPENCODE_PROXY_PORT=8080
# OPENCODE_DISABLE_TOOLS=true
# OPENCODE_PROXY_PROMPT_MODE=plugin-inject
EOF
  chmod 600 "$ENV_FILE"
  log_ok "配置已保存到 $ENV_FILE (600)"
}

validate_zen_key() {
  local k="$1"
  if [[ -z "$k" ]]; then return 0; fi
  if [[ ${#k} -lt 8 ]]; then
    log_warn "Zen Key 似乎过短（$((${#k})) chars），确认是否粘错？"
    return 1
  fi
  return 0
}

choose_menu() {
  # 简易数字菜单，兼容无 whiptail — 菜单输出到 stderr，返回值走 stdout
  {
    echo ""
    echo -e "${BOLD}请选择操作:${NC}"
    echo -e "  ${GREEN}1${NC}) 🧙  配置向导（交互式设置 API_KEY / Zen Key）"
    echo -e "  ${GREEN}2${NC}) 📦  一键打包 function.zip（Scaleway Functions）"
    echo -e "  ${GREEN}3${NC}) 🧪  本地联调（启动 handler，curl 健康检查）"
    echo -e "  ${GREEN}4${NC}) 🚀  部署到 Scaleway Functions（zip 上传）"
    echo -e "  ${GREEN}5${NC}) 🐳  部署到 Scaleway Containers（Docker）"
    echo -e "  ${GREEN}6${NC}) 🔍  查看当前配置与打包信息"
    echo -e "  ${GREEN}7${NC}) 🧹  清理（删除 zip / 临时文件）"
    echo -e "  ${GREEN}8${NC}) 📖  显示改动说明（最小兼容补丁）"
    echo -e "  ${GREEN}9${NC}) 🚪  退出"
    echo ""
  } >&2
  local choice
  choice=$(ask "输入编号" "1")
  echo "$choice"
}

show_changes() {
  hr
  echo -e "${BOLD}最小兼容改动清单（Scaleway 化）${NC}"
  echo ""
  echo -e "${CYAN}新增文件:${NC}"
  echo "  • handler.js                — Scaleway Functions 入口，export handle(event,context)，复用 src/proxy.createApp，经 serverless-http 适配 Express"
  echo "  • src/config.js             — 统一配置中心，抽离 index.js 重复逻辑，新增 isScalewayFunctionEnv() 探测，Functions 下默认 MANAGE_BACKEND=false、USE_ISOLATED_HOME=true、jail 在 /tmp"
  echo "  • scripts/pack-function.sh  — 纯打包脚本，被交互脚本复用"
  echo "  • scripts/scaleway-interactive.sh (本文件) — 极友好 TUI"
  echo "  • .scalewayignore / scaleway.toml 示例"
  echo ""
  echo -e "${CYAN}修改文件:${NC}"
  echo "  • package.json              — 新增依赖 serverless-http，新增脚本 dev:scaleway / pack:function / deploy:scaleway"
  echo "  • index.js                  — 重构为 import {buildConfig} from './src/config.js'，保留原行为，兼容 PORT 映射"
  echo "  • src/proxy.js              — ① import isScalewayFunctionEnv ② 修复 createRequestToolContext 重复 return 死代码 ③ ensureBackend 在 SCW 环境下快速失败并给出中文可操作 hint，jail 复用 /tmp"
  echo "  • entrypoint.sh             — 增加 PORT→OPENCODE_PROXY_PORT 映射 + SCW Functions 检测提示"
  echo "  • README.md                 — 新增 Scaleway 部署章节"
  echo "  • .gitignore                — 忽略 function.zip、.env.scaleway"
  echo ""
  echo -e "${CYAN}未改动:${NC}"
  echo "  • 核心代理逻辑、tool-runtime、API 路径完全保留，容器模式零感知"
  echo "  • 通过环境变量探测实现双模兼容：同一镜像/同一zip 在本地、Containers、Functions 均可运行"
  echo ""
  echo -e "${YELLOW}验证方式: npm test && bash scripts/pack-function.sh && npm run dev:scaleway${NC}"
  hr
}

show_config() {
  hr
  echo -e "${BOLD}当前配置快照${NC}"
  load_env
  echo -e "  API_KEY:                    ${GREEN}${API_KEY:-<空>}${NC} ${DIM}(${#API_KEY:-0} chars)${NC}"
  if [[ -n "${OPENCODE_ZEN_API_KEY:-}" ]]; then
    local masked="${OPENCODE_ZEN_API_KEY:0:6}****${OPENCODE_ZEN_API_KEY: -4}"
    echo -e "  OPENCODE_ZEN_API_KEY:       ${GREEN}$masked${NC} ${DIM}(${#OPENCODE_ZEN_API_KEY} chars)${NC}"
  else
    echo -e "  OPENCODE_ZEN_API_KEY:       ${YELLOW}<空> 将使用免费限流，额度每日 ~200次/${DIM}"
  fi
  echo -e "  OPENCODE_SERVER_PASSWORD:   ${GREEN}${OPENCODE_SERVER_PASSWORD:+****}${NC} ${DIM:-}${NC}"
  echo -e "  ENV 文件: $ENV_FILE  $(test -f $ENV_FILE && echo "存在" || echo "不存在")"
  echo -e "  ZIP: $FUNCTION_ZIP  $(test -f $FUNCTION_ZIP && echo "存在 $(du -h $FUNCTION_ZIP | cut -f1)" || echo "不存在")"
  echo -e "  Node: $(node --version 2>&1), npm: $(npm --version 2>&1)"
  if command -v scw >/dev/null 2>&1; then
    echo -e "  scw: $(scw version 2>&1 | head -n1)"
    echo -e "  scw project: $(scw account project list 2>&1 | head -n5 || echo "未登录")"
  fi
  hr
}

wizard() {
  hr
  echo -e "${BOLD}🧙 配置向导${NC} ${DIM}— 一次配置，多处复用${NC}"
  load_env
  local cur_api="${API_KEY:-}"
  local cur_zen="${OPENCODE_ZEN_API_KEY:-}"
  local cur_pw="${OPENCODE_SERVER_PASSWORD:-}"

  echo ""
  echo -e "${YELLOW}1/3 API_KEY${NC} — 用于保护你的 OpenAI 兼容端点的 Bearer Token"
  log_info "客户端需 Header: Authorization: Bearer <API_KEY>"
  log_info "留空将自动生成 32  hex 随机串（推荐）"
  local api_key
  api_key=$(ask_secret "请输入 API_KEY" "$cur_api")
  if [[ -z "$api_key" ]]; then
    api_key=$(generate_api_key)
    echo -e "${GREEN}  → 已生成随机 API_KEY: $api_key${NC}"
    log_info "请复制保存，下次回车保持不变"
  fi

  echo ""
  echo -e "${YELLOW}2/3 OPENCODE_ZEN_API_KEY${NC} — OpenCode Zen 的付费/免费 Key"
  log_info "获取： https://opencode.ai/zen → 登录 → Copy API Key"
  log_info "留空则使用匿名免费档（每日约 200 请求 / \$0.30，IP限流，见 README）"
  local zen_key
  zen_key=$(ask_secret "请输入 OPENCODE_ZEN_API_KEY" "$cur_zen")
  if [[ -n "$zen_key" ]]; then
    validate_zen_key "$zen_key" || {
      if ! confirm "仍使用此 Zen Key?" "y"; then
        zen_key=$(ask_secret "请重新输入 OPENCODE_ZEN_API_KEY" "$cur_zen")
      fi
    }
  else
    log_warn "未配置 Zen Key，将走免费限流；生产建议配置付费 Key"
  fi

  echo ""
  echo -e "${YELLOW}3/3 OPENCODE_SERVER_PASSWORD${NC} — opencode 后端密码（可选）"
  log_info "Functions 模式若 MANAGE_BACKEND=false 可留空"
  local server_pw
  server_pw=$(ask_secret "请输入 OPENCODE_SERVER_PASSWORD" "$cur_pw")
  # 允许空

  # 高级选项折叠
  echo ""
  if confirm "是否配置高级选项（端口/工具开关）?" "n"; then
    local adv_port adv_disable
    adv_port=$(ask "OPENCODE_PROXY_PORT" "${OPENCODE_PROXY_PORT:-10000}")
    adv_disable=$(ask "DISABLE_TOOLS (true/false)" "${DISABLE_TOOLS:-true}")
    # 暂存到 env，写入时追加
    export OPENCODE_PROXY_PORT="$adv_port"
    export DISABLE_TOOLS="$adv_disable"
  fi

  save_env "$api_key" "$zen_key" "$server_pw"
  # 同步到当前 shell
  export API_KEY="$api_key"
  export OPENCODE_ZEN_API_KEY="$zen_key"
  export OPENCODE_SERVER_PASSWORD="$server_pw"

  echo ""
  log_ok "配置完成！"
  echo -e "  客户端 Base URL (本地): ${CYAN}http://localhost:${OPENCODE_PROXY_PORT:-10000}/v1${NC}"
  echo -e "  客户端 Base URL (云端): ${CYAN}https://<your-function>.functions.fnc.fr-par.scw.cloud/v1${NC}"
  echo -e "  Header: ${CYAN}Authorization: Bearer $api_key${NC}"
  echo -e "  Model 示例: ${CYAN}opencode/big-pickle${NC} 或 ${CYAN}opencode/gpt-5-nano${NC}"
  hr
}

do_pack() {
  log_step "打包 $FUNCTION_ZIP"
  if [[ "$DRY_RUN" == true ]]; then
    log_info "[dry-run] 将执行: bash scripts/pack-function.sh"
    return
  fi
  # 复用独立打包脚本，保证一致
  bash "$ROOT_DIR/scripts/pack-function.sh"
  # 记录状态
  date -Iseconds > .scaleway.state 2>/dev/null || true
}

do_local_test() {
  log_step "本地联调"
  if [[ ! -f "$ENV_FILE" ]]; then
    log_warn "未找到 $ENV_FILE，先运行配置向导"
    wizard
  fi
  # shellcheck disable=SC1090
  set -a; source "$ENV_FILE" 2>/dev/null || true; set +a
  local port="${PORT:-8080}"
  log_info "启动 handler 本地仿真: node handler.js (port $port) …"
  log_info "另开终端执行: curl http://localhost:${port}/health  && curl http://localhost:${port}/v1/models -H \"Authorization: Bearer $API_KEY\""
  echo ""
  if confirm "现在启动本地服务?" "y"; then
    if [[ "$DRY_RUN" == true ]]; then
      log_info "[dry-run] node handler.js"
    else
      # 检查依赖
      if [[ ! -d node_modules/serverless-http ]]; then
        log_warn "serverless-http 未安装，执行 npm install ..."
        npm install --ignore-scripts
      fi
      PORT=$port node handler.js
    fi
  fi
}

deploy_function() {
  log_step "部署到 Scaleway Functions"
  if [[ ! -f "$FUNCTION_ZIP" ]]; then
    log_warn "$FUNCTION_ZIP 不存在，先打包"
    do_pack
  fi
  load_env
  if [[ -z "${API_KEY:-}" ]]; then
    log_err "API_KEY 未配置，请先运行配置向导"; return 1
  fi
  if ! command -v scw >/dev/null 2>&1; then
    hr
    echo -e "${YELLOW}未安装 scw CLI，无法一键部署。请选择:${NC}"
    echo "  1) 手动上传：Scaleway Console → Functions → Create Function → Upload Zip"
    echo "     Handler: handler.handle  Runtime: node22  Zip: $FUNCTION_ZIP"
    echo "     Env: API_KEY, OPENCODE_ZEN_API_KEY, OPENCODE_SERVER_PASSWORD"
    echo "  2) 安装 scw: curl -s https://raw.githubusercontent.com/scaleway/scaleway-cli/master/scripts/get.sh | sh"
    echo "     然后重新运行本脚本选 4"
    echo ""
    echo -e "  控制台: ${CYAN}https://console.scaleway.com/functions/namespaces${NC}"
    hr
    return
  fi

  # 交互式收集部署参数
  local fn_name fn_region fn_mem fn_timeout
  fn_name=$(ask "Function 名称" "opencode2api")
  fn_region=$(ask "Region" "fr-par")
  fn_mem=$(ask "Memory (128-2048 MB)" "512")
  fn_timeout=$(ask "Timeout (s)" "300")

  log_info "将使用 scw 部署到 $fn_region / $fn_name ..."
  if [[ "$DRY_RUN" == true ]]; then
    log_info "[dry-run] scw functions function create ... + deploy $FUNCTION_ZIP"
    return
  fi

  # 检查登录
  if ! scw account project list >/dev/null 2>&1; then
    log_err "scw 未登录，执行: scw init"
    if confirm "现在执行 scw init?" "y"; then scw init; else return 1; fi
  fi

  # 创建 namespace if needed? 简化：让用户先在控制台创建，或自动创建
  local ns_id
  ns_id=$(ask "Functions Namespace ID (留空自动创建)" "")
  if [[ -z "$ns_id" ]]; then
    log_info "尝试自动创建 namespace ..."
    # scw functions namespace create name=opencode2api region=fr-par
    if scw functions namespace create name=opencode2api region="$fn_region" 2>&1 | tee /tmp/scn.json; then
      ns_id=$(grep -o '"id"[[:space:]]*:[[:space:]]*"[^"]*"' /tmp/scn.json | head -n1 | cut -d'"' -f4)
      log_ok "创建 Namespace: $ns_id"
    else
      log_warn "自动创建失败，请手动在控制台创建 Namespace 并填入 ID"
      echo -e "  控制台: ${CYAN}https://console.scaleway.com/functions/namespaces${NC}"
      ns_id=$(ask "请粘贴 Namespace ID" "")
      if [[ -z "$ns_id" ]]; then log_err "未提供 Namespace"; return 1; fi
    fi
  fi

  # 创建或更新 function
  log_info "创建/更新函数 $fn_name ..."
  # 尝试 create，失败则视为已存在
  set +e
  scw functions function create name="$fn_name" namespace-id="$ns_id" runtime=node22 handler=handler.handle memory-limit="$fn_mem" timeout="${fn_timeout}s" region="$fn_region" \
    env.API_KEY="$API_KEY" env.OPENCODE_ZEN_API_KEY="${OPENCODE_ZEN_API_KEY:-}" env.OPENCODE_SERVER_PASSWORD="${OPENCODE_SERVER_PASSWORD:-}" \
    2>&1 | tee /tmp/fn_create.log
  local rc=$?
  set -e
  local fn_id
  fn_id=$(grep -o '"id"[[:space:]]*:[[:space:]]*"[^"]*"' /tmp/fn_create.log | head -n1 | cut -d'"' -f4)
  if [[ $rc -ne 0 ]]; then
    log_warn "create 失败，可能已存在，尝试获取已有函数 ID"
    fn_id=$(scw functions function list namespace-id="$ns_id" region="$fn_region" -o json 2>/dev/null | grep -o "\"name\":\"$fn_name\"[^}]*\"id\":\"[^\"]*\"" | grep -o '"id":"[^"]*"' | head -n1 | cut -d'"' -f4 || true)
    if [[ -z "$fn_id" ]]; then
      log_err "无法获取函数 ID，请检查控制台"; cat /tmp/fn_create.log; return 1
    fi
    log_info "找到已有函数 $fn_id，更新环境变量"
    scw functions function update function-id="$fn_id" region="$fn_region" env.API_KEY="$API_KEY" env.OPENCODE_ZEN_API_KEY="${OPENCODE_ZEN_API_KEY:-}" 2>&1 | tail -n20
  fi

  if [[ -z "$fn_id" ]]; then
    log_err "未获取到 function-id"; return 1
  fi

  log_info "上传 $FUNCTION_ZIP ..."
  scw functions function deploy function-id="$fn_id" region="$fn_region" zip-file="$FUNCTION_ZIP" 2>&1 | tail -n30
  log_ok "部署已提交，等待就绪..."
  sleep 3
  local fn_url
  fn_url=$(scw functions function get function-id="$fn_id" region="$fn_region" -o json 2>/dev/null | grep -o '"domain_name"[[:space:]]*:[[:space:]]*"[^"]*"' | head -n1 | cut -d'"' -f4 || true)
  if [[ -n "$fn_url" ]]; then
    echo ""
    echo -e "${GREEN}✓ 部署完成${NC}"
    echo -e "  URL: ${CYAN}https://$fn_url${NC}"
    echo -e "  Models: ${CYAN}curl https://$fn_url/v1/models -H \"Authorization: Bearer $API_KEY\"${NC}"
    echo -e "  Chat:   ${CYAN}curl https://$fn_url/v1/chat/completions -H \"Authorization: Bearer $API_KEY\" -d '{\"model\":\"opencode/big-pickle\",\"messages\":[{\"role\":\"user\",\"content\":\"hi\"}]}'${NC}"
    # 健康检查
    if confirm "现在做健康检查?" "y"; then
      curl -i "https://$fn_url/health" -H "Authorization: Bearer $API_KEY" || log_warn "健康检查失败，可能冷启动中，稍后重试"
    fi
  else
    log_warn "未获取到 URL，请到控制台查看: https://console.scaleway.com/functions/namespaces/$ns_id/functions"
  fi
}

deploy_container() {
  log_step "部署到 Scaleway Containers (Docker)"
  if ! command -v docker >/dev/null 2>&1; then
    log_err "docker 未安装"; return 1
  fi
  load_env
  local image_name registry region
  registry=$(ask "Container Registry (例 rg.fr-par.scw.cloud/<namespace>/opencode2api)" "rg.fr-par.scw.cloud/opencode2api/opencode2api:latest")
  region=$(ask "Region" "fr-par")

  log_info "构建 Docker 镜像 ..."
  if [[ "$DRY_RUN" == true ]]; then
    log_info "[dry-run] docker build -t $registry ."
    return
  fi
  docker build -t "$registry" .

  log_info "推送镜像 ..."
  docker push "$registry"

  if command -v scw >/dev/null 2>&1; then
    if confirm "是否通过 scw 一键创建/更新 Container?" "y"; then
      local ns_id
      ns_id=$(ask "Containers Namespace ID" "")
      if [[ -n "$ns_id" ]]; then
        scw container container create namespace-id="$ns_id" name=opencode2api region="$region" registry-image="$registry" port=10000 \
          env.API_KEY="$API_KEY" env.OPENCODE_ZEN_API_KEY="${OPENCODE_ZEN_API_KEY:-}" || \
        log_warn "创建失败，可能已存在，请在控制台更新镜像"
        log_ok "请到 https://console.scaleway.com/containers/namespaces/$ns_id/containers 查看"
      fi
    fi
  else
    log_info "请到控制台手动创建 Container，镜像: $registry"
    echo -e "  控制台: ${CYAN}https://console.scaleway.com/containers${NC}"
  fi
}

do_clean() {
  log_step "清理"
  rm -f "$FUNCTION_ZIP" /tmp/pack.log /tmp/fn_create.log /tmp/scn.json
  log_ok "已清理 $FUNCTION_ZIP"
  if confirm "是否也删除 $ENV_FILE ?" "n"; then
    rm -f "$ENV_FILE"
    log_ok "已删除 $ENV_FILE"
  fi
}

print_help() {
  cat <<HELP
Usage: $0 [选项]
  无参数      交互式主菜单（推荐）
  --pack      仅打包 function.zip
  --wizard    仅运行配置向导
  --test      本地联调
  --deploy-fn 部署到 Functions
  --deploy-ct 部署到 Containers
  --clean     清理
  --yes       非交互（配合 --pack 使用，读取已有 $ENV_FILE）
  --dry-run   只打印将执行的操作
  --help      显示此帮助

Examples:
  $0                          # 交互式
  $0 --pack --yes            # CI 打包
  OPENCODE_ZEN_API_KEY=sk-... $0 --wizard --yes
  $0 --deploy-fn --yes

Env vars (也可写入 $ENV_FILE):
  API_KEY, OPENCODE_ZEN_API_KEY, OPENCODE_SERVER_PASSWORD
HELP
}

# ─────────────────────────────────────────────
# 参数解析
# ─────────────────────────────────────────────
DO_WIZARD=false
while [[ $# -gt 0 ]]; do
  case "$1" in
    --pack) DO_PACK=true; shift ;;
    --test) DO_TEST=true; shift ;;
    --wizard) DO_WIZARD=true; shift ;;
    --deploy-fn) DO_DEPLOY_FN=true; shift ;;
    --deploy-ct) DO_DEPLOY_CT=true; shift ;;
    --clean) DO_CLEAN=true; shift ;;
    --yes) NON_INTERACTIVE=true; shift ;;
    --dry-run) DRY_RUN=true; shift ;;
    -h|--help) print_help; exit 0 ;;
    *) log_warn "未知参数 $1"; print_help; exit 1 ;;
  esac
done

# 非交互批量（含 wizard）
if [[ "$DO_WIZARD" == true || "$DO_PACK" == true || "$DO_DEPLOY_FN" == true || "$DO_DEPLOY_CT" == true || "$DO_CLEAN" == true || "$DO_TEST" == true ]]; then
  if [[ "$DO_WIZARD" == true ]]; then
    # banner 仅在非 --yes 时显示完整，CI 时简化
    if [[ "$NON_INTERACTIVE" != true ]]; then banner; fi
    check_deps
    load_env
    wizard
    # 若仅 wizard 则退出，否则继续其他动作
    if [[ "$DO_PACK" == false && "$DO_DEPLOY_FN" == false && "$DO_DEPLOY_CT" == false && "$DO_CLEAN" == false && "$DO_TEST" == false ]]; then
      exit 0
    fi
  fi
  if [[ "$DO_PACK" == true || "$DO_DEPLOY_FN" == true || "$DO_DEPLOY_CT" == true || "$DO_CLEAN" == true || "$DO_TEST" == true ]]; then
    if [[ "$DO_WIZARD" == false ]]; then
      banner
      check_deps
      load_env
    fi
    [[ "$DO_PACK" == true ]] && do_pack
    [[ "$DO_TEST" == true ]] && do_local_test
    [[ "$DO_DEPLOY_FN" == true ]] && deploy_function
    [[ "$DO_DEPLOY_CT" == true ]] && deploy_container
    [[ "$DO_CLEAN" == true ]] && do_clean
    exit 0
  fi
fi

# ─────────────────────────────────────────────
# 交互主循环
# ─────────────────────────────────────────────
banner
check_deps
load_env

while true; do
  choice=$(choose_menu)
  case "$choice" in
    1) wizard ;;
    2) do_pack ;;
    3) do_local_test ;;
    4) deploy_function ;;
    5) deploy_container ;;
    6) show_config ;;
    7) do_clean ;;
    8) show_changes ;;
    9) echo -e "${GREEN}再见！${NC}"; exit 0 ;;
    *) log_warn "无效选择 $choice" ;;
  esac
  echo ""
  if ! confirm "返回主菜单?" "y"; then
    echo -e "${GREEN}再见！${NC}"; exit 0
  fi
done
